library(shiny)
library(RCurl)
print("I'm in a new log")
library(rjson)
library(janitor)
library(tibble)
library(tidyr)
library(dplyr)
library(DT)
library(stringr)
library(shinydashboard)
library(shinycssloaders)
library(formattable)
library(plotly)
library(reshape)

raw_selections <- read.csv("./Data/raw_selections_real.csv")
standings <- read.csv("./Data/scores_temp.csv")
standings <- standings %>% arrange(desc(Score))
master <- read.csv("./Data/all_teams.csv", stringsAsFactors = FALSE)  
